# Generated by Django 4.2 on 2023-04-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expence', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=4)),
                ('Entry_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
