# Generated by Django 4.2 on 2023-04-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_expences_c_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expences',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
