# Generated by Django 4.2 on 2023-04-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_expences_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expences',
            name='c_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
