# Generated by Django 4.1.8 on 2023-04-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_expences_c_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000017E450F1FC0>', max_length=200),
        ),
    ]
