# Generated by Django 4.1.8 on 2023-04-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_customer_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='uid',
        ),
    ]
