# Generated by Django 4.1.8 on 2023-04-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_onetimepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001F8AE921FC0>', max_length=200),
        ),
    ]
