# Generated by Django 4.1.8 on 2023-04-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_alter_onetimepassword_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='uid',
            field=models.CharField(blank=True, default='<function uuid4 at 0x00000128589BE050>', max_length=200, null=True),
        ),
    ]
